### ISSUE TITLE
UnhandledPromiseRejection

### ISSUE THREAD

**Issue by andrasdenes** [Sorunome/mx-puppet-twitter#7]
```
(node:11704) UnhandledPromiseRejectionWarning: Error: Forbidden.
    at Request._callback (.................../mx-puppet-twitter/node_modules/twitter-webhooks/lib/helpers.js:27:33)
    at Request.self.callback (................/mx-puppet-twitter/node_modules/request/request.js:185:22)
    at Request.emit (events.js:196:13)
    at Request.<anonymous> (................/mx-puppet-twitter/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:196:13)
    at IncomingMessage.<anonymous> (................/mx-puppet-twitter/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:284:20)
    at IncomingMessage.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
(node:11704) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11704) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Can anyone please help with this? I really am unsure what is wrong here.
I think It is becasue of this issue, that the bot will not even register to my server.

**Comment by Sorunome** [comment]
Did you set up the reverse proxy correctly? Does the reverse proxy unravel https?

**Comment by Sorunome** [comment]
Are you having the same issue as #5 (not setting "account activity" as type)

**Comment by andrasdenes** [comment]
Seems to be the case. Thank you!
